version: '3.8'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/music-order-app
      - JWT_SECRET=your_jwt_secret
      - ADMIN_USERNAME=your_admin_username
      - ADMIN_PASSWORD=your_admin_password
      - CLIENT_URL=your_client_url
      - SOCKET_URL=your_socket_url
      - YOUTUBE_API_KEY=your_youtube_api_key
      - BTC_API_KEY=your_btc_api_key
    ports:
      - '5800:5000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=your_api_url
        - VITE_SOCKET_URL=your_socket_url
    ports:
      - '3800:80'

networks:
  music-order-network:
    driver: bridge

volumes:
  mongodb_data: