version: '3.8'

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: music-order-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: music-order-app
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - music-order-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: music-order-api
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/music-order-app
      - JWT_SECRET=your_jwt_secret_key
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - CLIENT_URL=http://localhost:8080
      - SOCKET_URL=http://localhost:5800
      - YOUTUBE_API_KEY=your_youtube_api_key
      - BTC_API_KEY=your_btc_api_key
      - WEATHER_API_KEY=your_weather_api_key
      - WEATHER_LOCATION=21.0051906,105.7387209
    ports:
      - '5800:5000'
    networks:
      - music-order-network
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  lunch-vote-mf:
    build:
      context: ./lunch-vote-mf
      dockerfile: Dockerfile
    container_name: music-order-lunch-vote-mf
    restart: unless-stopped
    ports:
      - '5806:80'
    networks:
      - music-order-network

  poliboard:
    build:
      context: ./poliboard
      dockerfile: Dockerfile
    container_name: music-order-poliboard
    restart: always
    ports:
      - '5807:80'
    networks:
      - music-order-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5800
        VITE_SOCKET_URL: http://localhost:5800
        VITE_LUNCH_VOTE_REMOTE_URL: http://localhost:5806/assets/remoteEntry.js
        VITE_POLIBOARD_REMOTE_URL: http://localhost:5807/assets/remoteEntry.js
    container_name: music-order-client
    restart: unless-stopped
    depends_on:
      - api
      - lunch-vote-mf
      - poliboard
    environment:
      - VITE_API_URL=http://localhost:5800
      - VITE_SOCKET_URL=http://localhost:5800
      - VITE_RESPONSIVE_VOICE_KEY=your_responsive_voice_key
    ports:
      - '3800:80'
    networks:
      - music-order-network

networks:
  music-order-network:
    driver: bridge

volumes:
  mongodb_data:
